baseURL = 'localhost'
locale = 'en-us'
title = 'My New Hugo Project'
theme = 'hugo-xmin'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier  = "about"
    name        = "about"
    url         = "about/"

  [[menu.main]]
    identifier  = "stuff"
    name        = "stuff"
    url         = "stuff/"